server:
  port: 8080
spring:
  application:
    name: search-sample
  devtools:
    add-properties: true
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/jpa_ex}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:12345678}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      continue-on-error: true
      data-locations: classpath:data.sql
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
app:
  upload-dir: D:\egs_train

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
openapi:
  service:
    api-docs: api-service
    server: http://localhost:${server.port}
    title: API Document
    version: 1.0.0

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

    # app
    com.example.demo: DEBUG
    com.example.demo.user: TRACE
    com.example.demo.service: WARN
    com.example.demo.repository: ERROR

    # spring
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    org.springframework.jdbc.core: TRACE

  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n"




