spring:
  application:
    name: authn_jwt



logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: TRACE
#    org.springframework.boot.autoconfigure: DEBUG

jwt:
  private.key: classpath:app.key
  public.key: classpath:app.pub