server:
  port: 8081

spring:
  application:
    name: keycloak_ex
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/demo-realm

logging:
  level:
    root: INFO


    org.springframework.security.oauth2: DEBUG
    org.springframework.web.filter: DEBUG
    # spring
    org.springframework.web: debug
    org.springframework.security: DEBUG
    org.logging.level.org.springframework.security.web.FilterChainProxy: TRACE
    org.logging.level.org.springframework.security.web.context: TRACE
    org.logging.level.org.springframework.security.authentication: TRACE
    org.logging.level.org.springframework.security.authorization: TRACE

  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n"

idp:
  url: http://localhost:8080
  client-id: backend-service
  client-secret: Q8bfAxKLJVjXV0Y7YHol1fDHTPNUWMNg